### ISSUE TITLE
Addressable resources not unloaded within bundle

### ISSUE THREAD

**Issue by elringus** [naninovel/docs#159]
Caused by the Unity bug: https://issuetracker.unity3d.com/product/unity/issues/guid/UUM-37775

Please vote on the tracker to make it fixed as soon as possible.

Associated forum thread: https://forum.unity.com/threads/resources-unloadunusedassets-cannot-unload-assets-without-any-references.1088116/#post-8991523

Use `Package Separately` for a temporary workaround.

**Comment by Artein** [comment]
Most probably you need to update this Issue and documentation, cause the ticket is closed "by design" and Unity updated Addressables documentation

**Comment by Elringus** [comment]
I know, I'm in touch with them. They've already close it twice before and then re-opened.

**Comment by elringus** [comment]
Looks like this won't be resolved on the Unity side any time soon, so I've added `Label By Scripts` option to the resource provider configuration in v1.20.

When the option is enabled (default) all the Naninovel addressable assets will be labeled by the scripts in which they’re used. Given `Bundle Mode` of the addressable group is set to `Pack Together By Label`, asset bundles will then be optimized for the project scenario structure improving load times and RAM usage.

Documentation: https://pre.naninovel.com/guide/resource-providers#script-labels
