### ISSUE TITLE
Voice map unvisible string

### ISSUE THREAD

**Issue by Bicardine** [naninovel/docs#164]
If use Russian characters and short sentences started with "—"  sometimes Nani does not see these lines in voice map. The issue is solved if increase the length of the sentence or add an empty character to the end of the sentence or use eng characters instead of rus.

Or just remove "—" but it's used intentionally creating a book wibe.

![Issue](https://github.com/naninovel/docs/assets/83329675/4c2e7669-ebe8-4207-8158-1b6a20077ffc)

**Comment by elringus** [comment]
Please contact support: https://naninovel.com/support/#naninovel-support
We're not providing support via github.
