### ISSUE TITLE
PerformOnGameDeserializeTasksAsync() and cycle shifted

### ISSUE THREAD

**Issue by Bicardine** [naninovel/docs#165]
PerformOnGameDeserializeTasksAsync() and it's "for" cycle which is shifted if a new AddOnGameDeserializeTask at this moment so index offset and cycle don't work with it. 

AddOnGameDeserializeTask can be invoked when PerformOnGameDeserializeTasksAsync() works and this time another object enabled which have OnEnable add listener Deserialization task wich cannot process Nani correctly as in my case.

![iss](https://github.com/naninovel/docs/assets/83329675/2557d39d-7279-4de3-ab00-4e8bb1dcb4f4)

Therefore, it caused bugs in my case. Maybe we should make more dynamic logic or at least prohibit calling a function until it is finished?

For my case I changed the code using @override

` protected override void PerformOnGameSerializeTasks(GameStateMap state)
        {
            for (int i = 0; i < _onGameSerializeTasks.Count; i++)
                _onGameSerializeTasks[i](state);
        }

        protected override async UniTask PerformOnGameDeserializeTasksAsync(GameStateMap state)
        {
            for (int i = 0; i < _onGameDeserializeTasks.Count; i++)
                await _onGameDeserializeTasks[i](state);
        }`

Although the above code does not solve the problem that the task can be deleted during the loop for example.

**Comment by elringus** [comment]
Please contact support: https://naninovel.com/support/#naninovel-support
We're not providing support via github.
