### ISSUE TITLE
Story Flow Diagram Editing +everything else in 1 place in the script graph

### ISSUE THREAD

**Issue by katrinshtorm** [naninovel/docs#166]
Hello. Please add the ability to edit dialogues in the form of nodes (like the script graph is implemented now), but also for text/dialogues. This would allow editing dialogues not in a side menu but directly within the node, and then creating other nodes with dialogues/responses.

Similar to how you have implemented the connection between NaniScript scripts in the script graph, but with the ability to click on a script to enter it and have the entire script represented as editable nodes.

Because right now, editing text/actions is an indescribable pain.

Visual Scripting/Naninovel script graph currently does not have such convenient regulation/editing (in 1 place).

![gh](https://github.com/naninovel/docs/assets/77185151/94cef9e3-d67a-4401-a5d7-affd243e230b)
smp 2
![image](https://github.com/naninovel/docs/assets/77185151/231a961f-2459-4941-9a2b-bff3764c2e69)

**Comment by elringus** [comment]
Hi, Please start a topic on the forum or on Discord. Issues on GitHub are not for community discussions.
